"""Markdown file generator for video analysis results."""
import logging
from pathlib import Path
from datetime import datetime
import re
import config

logger = logging.getLogger(__name__)


class MarkdownGenerator:
    """Generates markdown files from video analysis results."""

    def __init__(self):
        """Initialize the markdown generator."""
        if not config.SAVE_MD_WITH_VIDEO:
            config.SUMMARIES_DIR.mkdir(exist_ok=True)

    def generate(self, analysis_result: dict, video_path: Path) -> Path:
        """
        Generate a markdown file from analysis results.

        Args:
            analysis_result: Dict with title, subtitle, introduction, steps, and conclusion
            video_path: Path object to the original video file

        Returns:
            Path to the created markdown file
        """
        title = analysis_result["title"]
        subtitle = analysis_result["subtitle"]
        introduction = analysis_result["introduction"]
        steps = analysis_result["steps"]
        conclusion = analysis_result["conclusion"]

        # Generate safe filename from title
        safe_filename = self._sanitize_filename(title)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        md_filename = f"{timestamp}_{safe_filename}.md"

        # Save in same directory as video or in summaries folder
        if config.SAVE_MD_WITH_VIDEO:
            md_path = video_path.parent / md_filename
        else:
            md_path = config.SUMMARIES_DIR / md_filename

        # Generate markdown content with blog-post structure
        current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        markdown_content = f"""# {title}

*{subtitle}*

---

**📹 Video Source**: `{video_path.name}`
**📂 Location**: `{video_path.parent}`
**📅 Generated**: {current_date}

---

{introduction}

---

"""

        # Add each step - they now come with their own markdown formatting (### headers, bullets, etc.)
        for step in steps:
            markdown_content += f"{step}\n\n"

        # Add conclusion
        markdown_content += f"""
---

{conclusion}

---

*📝 Generated by ScreenPulse - AI-Powered Video Analysis System*
*🤖 Powered by Gemini 2.0 Flash Lite*
*⏰ Created on {current_date}*
"""

        # Write to file
        md_path.write_text(markdown_content, encoding='utf-8')
        logger.info(f"Created markdown file: {md_path.name}")

        return md_path

    def _sanitize_filename(self, title: str) -> str:
        """
        Convert title to a safe filename.

        Args:
            title: The title string

        Returns:
            Sanitized filename (without extension)
        """
        # Remove or replace invalid filename characters
        safe = re.sub(r'[<>:"/\\|?*]', '', title)
        # Replace spaces with underscores
        safe = safe.replace(' ', '_')
        # Remove multiple underscores
        safe = re.sub(r'_+', '_', safe)
        # Limit length
        safe = safe[:50]
        # Remove leading/trailing underscores
        safe = safe.strip('_')
        # Convert to lowercase
        safe = safe.lower()

        return safe if safe else "video_summary"
