"""Markdown file generator for video analysis results."""
import logging
from pathlib import Path
from datetime import datetime
import re
import config

logger = logging.getLogger(__name__)


class MarkdownGenerator:
    def __init__(self):
        if not config.SAVE_MD_WITH_VIDEO:
            config.SUMMARIES_DIR.mkdir(exist_ok=True)

    def generate(self, analysis_result: dict, video_path: Path) -> Path:
        title = analysis_result["title"]
        summary = analysis_result["summary"]
        steps = analysis_result["steps"]

        safe_filename = self._sanitize_filename(title)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        md_filename = f"{timestamp}_{safe_filename}.md"

        if config.SAVE_MD_WITH_VIDEO:
            md_path = video_path.parent / md_filename
        else:
            md_path = config.SUMMARIES_DIR / md_filename

        current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        markdown_content = f"""# {title}

**Date**: {current_date}
**Source**: {video_path.name}
**Location**: {video_path.parent}

## Summary

{summary}

## Steps

"""
        for i, step in enumerate(steps, 1):
            step_text = re.sub(r'^Step \d+:\s*', '', step)
            markdown_content += f"{i}. {step_text}\n"

        markdown_content += f"""\n---\n*Generated by ScreenPulse on {current_date}*\n"""
        md_path.write_text(markdown_content, encoding='utf-8')
        logger.info(f"Created markdown file: {md_path.name}")
        return md_path

    def _sanitize_filename(self, title: str) -> str:
        safe = re.sub(r'[<>:"/\\|?*]', '', title)
        safe = safe.replace(' ', '_')
        safe = re.sub(r'_+', '_', safe)
        safe = safe[:50].strip('_').lower()
        return safe if safe else "video_summary"
